//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rr.Provider.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rr.Provider.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPTY.
        /// </summary>
        public static string RES_EMPTY {
            get {
                return ResourceManager.GetString("RES_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RES_EMPTY_VALUE_MESSAGE_DEVICE_INIT.
        /// </summary>
        public static string RES_EMPTY_VALUE_MESSAGE_DEVICE_INIT {
            get {
                return ResourceManager.GetString("RES_EMPTY_VALUE_MESSAGE_DEVICE_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RES_EMPTY_VALUE_MESSAGE_GROUND_OPE.
        /// </summary>
        public static string RES_EMPTY_VALUE_MESSAGE_GROUND_OPE {
            get {
                return ResourceManager.GetString("RES_EMPTY_VALUE_MESSAGE_GROUND_OPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RES_EMPTY_VALUE_MESSAGE_OUTSIDE_OPE.
        /// </summary>
        public static string RES_EMPTY_VALUE_MESSAGE_OUTSIDE_OPE {
            get {
                return ResourceManager.GetString("RES_EMPTY_VALUE_MESSAGE_OUTSIDE_OPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RES_EMPTY_VALUE_NAME_DEVICE_INIT.
        /// </summary>
        public static string RES_EMPTY_VALUE_NAME_DEVICE_INIT {
            get {
                return ResourceManager.GetString("RES_EMPTY_VALUE_NAME_DEVICE_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RES_EMPTY_VALUE_NAME_GROUND_OPE.
        /// </summary>
        public static string RES_EMPTY_VALUE_NAME_GROUND_OPE {
            get {
                return ResourceManager.GetString("RES_EMPTY_VALUE_NAME_GROUND_OPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RES_EMPTY_VALUE_NAME_OUTSIDE_OPE.
        /// </summary>
        public static string RES_EMPTY_VALUE_NAME_OUTSIDE_OPE {
            get {
                return ResourceManager.GetString("RES_EMPTY_VALUE_NAME_OUTSIDE_OPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RES_EMPTY_VALUE_SPEECH_TEXT_DEVICE_INIT.
        /// </summary>
        public static string RES_EMPTY_VALUE_SPEECH_TEXT_DEVICE_INIT {
            get {
                return ResourceManager.GetString("RES_EMPTY_VALUE_SPEECH_TEXT_DEVICE_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RES_EMPTY_VALUE_SPEECH_TEXT_GROUND_OPE.
        /// </summary>
        public static string RES_EMPTY_VALUE_SPEECH_TEXT_GROUND_OPE {
            get {
                return ResourceManager.GetString("RES_EMPTY_VALUE_SPEECH_TEXT_GROUND_OPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RES_EMPTY_VALUE_SPEECH_TEXT_OUTSIDE_OPE.
        /// </summary>
        public static string RES_EMPTY_VALUE_SPEECH_TEXT_OUTSIDE_OPE {
            get {
                return ResourceManager.GetString("RES_EMPTY_VALUE_SPEECH_TEXT_OUTSIDE_OPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string RES_FALSE {
            get {
                return ResourceManager.GetString("RES_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RES_FALSE_VALUE_SPEECH_ENABLE_DEVICE_INIT.
        /// </summary>
        public static string RES_FALSE_VALUE_SPEECH_ENABLE_DEVICE_INIT {
            get {
                return ResourceManager.GetString("RES_FALSE_VALUE_SPEECH_ENABLE_DEVICE_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RES_FALSE_VALUE_SPEECH_ENABLE_GROUND_OPE.
        /// </summary>
        public static string RES_FALSE_VALUE_SPEECH_ENABLE_GROUND_OPE {
            get {
                return ResourceManager.GetString("RES_FALSE_VALUE_SPEECH_ENABLE_GROUND_OPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RES_FALSE_VALUE_SPEECH_ENABLE_OUTSIDE_OPE.
        /// </summary>
        public static string RES_FALSE_VALUE_SPEECH_ENABLE_OUTSIDE_OPE {
            get {
                return ResourceManager.GetString("RES_FALSE_VALUE_SPEECH_ENABLE_OUTSIDE_OPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -400.
        /// </summary>
        public static string RES_HANDLERS_CLEAR_CODE {
            get {
                return ResourceManager.GetString("RES_HANDLERS_CLEAR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -80.
        /// </summary>
        public static string RES_NEXT_MODEL_CODE {
            get {
                return ResourceManager.GetString("RES_NEXT_MODEL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NONE.
        /// </summary>
        public static string RES_NONE {
            get {
                return ResourceManager.GetString("RES_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rr.Beechcraft_Turbine_Duke.
        /// </summary>
        public static string RES_PROFILE_NAME {
            get {
                return ResourceManager.GetString("RES_PROFILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -50.
        /// </summary>
        public static string RES_SPEECH_DISABLE_CODE {
            get {
                return ResourceManager.GetString("RES_SPEECH_DISABLE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -40.
        /// </summary>
        public static string RES_SPEECH_DONE_CODE {
            get {
                return ResourceManager.GetString("RES_SPEECH_DONE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string RES_TRUE {
            get {
                return ResourceManager.GetString("RES_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER_ACTION_CODE.
        /// </summary>
        public static string RES_USER_ACTION_CODE {
            get {
                return ResourceManager.GetString("RES_USER_ACTION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string RES_ZERO_STRING {
            get {
                return ResourceManager.GetString("RES_ZERO_STRING", resourceCulture);
            }
        }
    }
}
